# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - backlog
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. If this
  was a feature request that others have shown no interest in then it's
  likely to not get implemented due to lack of interest. If others also
  want to see this feature then now is the time to say something!
  Thank you for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
exemptMilestones: true

# Since old PRs are less useful than old issues ping them sooner.
pulls:
  daysUntilStale: 30
  markComment: >
    This pull request has not had any activity in 30 days. Since things move fast it's best 
    to get PRs merged in. If this PR addresses a previously filed issue that needs to be
    resolved please work to get it merged in, or allow somebody else to work on a fix.
    This PR will be closed if no further activity occurs. Thank you for your contributions!
  exemptLabels:
      - bot
