name: Build nightly docker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:

      - name: Log into GitHub Container Registry
        env: 
          GH_CR_PAT: ${{ secrets.GH_CR_PAT }}
        run: echo "${{ secrets.GH_CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
        if: env.GH_CR_PAT != null

      - uses: actions/checkout@v3
      - name: Setup and run
        env: 
          GH_CR_PAT: ${{ secrets.GH_CR_PAT }}
        run: cd build/release && ./docker-nightly.sh
        if: env.GH_CR_PAT != null
