name: Format Javascript

# This action works with pull requests and pushes
on:
  push:
    branches:
    - develop

jobs:
  prettier:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Prettify code
      uses: creyD/prettier_action@v4.2
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write webroot/**/*.{js,md}
        only_changed: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
